### ISSUE TITLE
Cannot set property 'submenu'

### ISSUE THREAD

**Issue by fridzema** [mubaidr/vue-electron-template#338] opened 2019-07-10 12:39 UTC
Hello, 

After a fresh install and running `npm run debug` i get the following error:
![Screenshot 2019-07-10 at 14 37 47](https://user-images.githubusercontent.com/8180660/60969696-72b11680-a320-11e9-9c9b-c340b9dd62d1.png)

Anyone else experiencing this?

**Comment by mubaidr** [comment] 2019-07-10 14:16
The issue is here: https://github.com/mubaidr/vue-electron-template/blob/master/src/main/index.js#L193

please remove following content from the above file: 
```js
// Edit menu
    template[1].submenu.push(
      // @ts-ignore
      { type: 'separator' },
      {
        label: 'Speech',
        submenu: [{ role: 'startspeaking' }, { role: 'stopspeaking' }],
      }
    )

    // Window menu
    template[3].submenu = [
      { role: 'close' },
      { role: 'minimize' },
      { role: 'zoom' },
      { type: 'separator' },
      { role: 'front' },
    ]
```

I missed it because I don't have macos. I will update the template.

**Comment by mubaidr** [comment] 2019-07-10 14:18
Should be fixed in: https://github.com/mubaidr/vue-electron-template/commit/c00f0ada2df6e7b9f26a0b576fceb96c26d8afd3

**Closed by mubaidr** 2019-07-10 14:18 UTC
